# fly.toml app configuration file generated for blog-api-eishalex on 2023-12-04T15:59:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blog-api-eishalex"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
